# Generated by Django 6.0.3 on 2026-03-11 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "embedding_model",
                    models.CharField(default="text-embedding-3-small", max_length=100),
                ),
                ("vector_size", models.IntegerField(default=1536)),
                ("chunk_size", models.IntegerField(default=512)),
                ("chunk_overlap", models.IntegerField(default=64)),
                ("retrieval_top_k", models.IntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("doc_count", models.IntegerField(default=0)),
                ("chunk_count", models.IntegerField(default=0)),
                ("settings", models.JSONField(default=dict)),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_bases",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_bases",
            },
        ),
    ]
