# Generated by Django 6.0.3 on 2026-03-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_bases", "0002_kb_rebuild"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="knowledgebase",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="kb_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
