# Generated by Django 6.0.3 on 2026-03-11 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge_bases", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("file", "File"), ("url", "URL"), ("faq", "FAQ")],
                        max_length=50,
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, max_length=1000)),
                ("source_url", models.CharField(blank=True, max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsing", "Parsing"),
                            ("parsed", "Parsed"),
                            ("chunking", "Chunking"),
                            ("chunked", "Chunked"),
                            ("embedding", "Embedding"),
                            ("indexed", "Indexed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("chunk_count", models.IntegerField(default=0)),
                ("word_count", models.IntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=10)),
                ("meta", models.JSONField(default=dict)),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="knowledge_bases.knowledgebase",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chunk_index", models.IntegerField()),
                ("text", models.TextField()),
                ("text_length", models.IntegerField()),
                ("token_count", models.IntegerField(blank=True, null=True)),
                ("page", models.IntegerField(blank=True, null=True)),
                ("section", models.CharField(blank=True, max_length=500)),
                ("embedding_model", models.CharField(blank=True, max_length=100)),
                ("vector_id", models.CharField(blank=True, max_length=255)),
                ("is_embedded", models.BooleanField(db_index=True, default=False)),
                ("meta", models.JSONField(default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.document",
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge_bases.knowledgebase",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "document_chunks",
                "ordering": ["chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="URLSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=2000)),
                (
                    "render_mode",
                    models.CharField(
                        choices=[
                            ("static", "Static"),
                            ("selenium", "Selenium"),
                            ("playwright", "Playwright"),
                        ],
                        default="static",
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=50)),
                ("crawl_depth", models.IntegerField(default=0)),
                ("last_crawled_at", models.DateTimeField(blank=True, null=True)),
                ("html_path", models.CharField(blank=True, max_length=1000)),
                ("meta", models.JSONField(default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="url_source",
                        to="documents.document",
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="url_sources",
                        to="knowledge_bases.knowledgebase",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "url_sources",
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.IntegerField(default=1)),
                ("file_path", models.CharField(blank=True, max_length=1000)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "document_versions",
                "unique_together": {("document", "version")},
            },
        ),
    ]
